### PR TITLE
Xml syntax check

### PR DESCRIPTION
**Pull request by bam95899**

### CODE REVIEW

**Review by phg49389 — APPROVED** [review]

**Review by c-schwarze — APPROVED** [review]

**Comment by c-schwarze** [comment]
@bam95899 did this end up fixing the issue?

**Comment by bam95899** [comment]
@c-schwarze I was never able to replicate the issue locally, so I'm not sure if this PR would fix the issue or not.

**Comment by c-schwarze** [comment]
Gotcha, I'll go ahead and pull this branch onto master directly. If it fixes the issue, then we can merge.

**Comment by bam95899** [comment]
The server has been on this branch for a week and no new sentry `/opt/sitemap/sitemap.xml:1:0: no element found` errors have occurred. Do you think we are good to merge @c-schwarze?

**Comment by c-schwarze** [comment]
Yeah it looks good! Go ahead and merge/pull on the server 👍

**Pull request merged**
